### ISSUE TITLE
Key Ring Setting

### ISSUE THREAD

**Issue by 1ccb** [heilingbrunner/vscode-gnupg-tool#3]
Can we get a simple vscode setting to point to the key ring?

**Comment by heilingbrunner** [comment]
I thought i solved this issue with issue #1. A single vscode setting prevents you having more than one alternate keyrings. Open VSCode in the folder with the alternate keyring, and the extension will use this one. Otherwise it will use the default keyring.
Is there is better reason having a single VSCode setting ?

**Comment by heilingbrunner** [comment]
I will check for a vscode setting. I used the feature above only for key management. Your setting will be fine for general de- and encryption.

**Comment by 1ccb** [comment]
A setting in VSCode can exist at the user, workspace or folder level.  This allows for the use of different keyrings for different projects/workspaces and the folder that I'm working in doesn't have to contain my keyring.

**Comment by heilingbrunner** [comment]
In progress ...

**Comment by heilingbrunner** [comment]
I added a setting to vscode. Now there is an order of the homedir usage:

1. Detect local key ring in the workspace
2. When not 1. , use vscode homedir setting
3. When not 2. , use default key ring

**Comment by 1ccb** [comment]
Perfect - thank you!
